name: Show Secret Value

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unmask secret
        run: echo "::add-mask::${{ secrets.QWERTY }}"

      - name: Show secret value
        run: echo "The secret value is: ${{ secrets.QWERTY }}"
